# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  	config.vm.define "web" do |web|
	web.vm.box = "centos/7"
	web.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (4) I219-V", ip: "192.168.2.70"
  end
  
	  config.vm.define "db" do |db|
	  db.vm.box = "centos/7"
	  db.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (4) I219-V", ip: "192.168.2.71"
  end
  
 	  config.vm.define "w10" do |w10|
	  w10.vm.box = "vdelarosa/windows-10"
	  w10.vm.network "public_network"#, bridge: "Intel(R) Ethernet Connection (4) I219-V", ip: "192.168.2.72"
  end

	  config.vm.define "app" do |app|
	  app.vm.box = "centos/7"
	  app.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (4) I219-V", ip: "192.168.2.73"
  end
end